### ISSUE TITLE
MacOsx moving the scene does not work

### ISSUE THREAD

**Issue by jymen** [UnderwaterApps/overlap2d#100]
Not sure about this one : 
by looking at existing overlap2D videos it seems that , when a project is opened , left clicking on the background and moving the mouse makes the background view moving.(a kind of camera move)

is that correct ? 

if yes then on MacOsx this mouse gesture just draws a temporary rectangle on the screen until the mouse button is released.

If this is a mac bug can you just give me a starting point in the code where the moving background  semantics takes place ... so I can try to determine what's the problem is on mac and trying to fix it

**Comment by azakhary** [comment]
There are 2 ways to pan the scene.
1) Middle click and drag
2) Press Space and drag.

I guess if you are using touchpad you have to use method 2.

**Comment by azakhary** [comment]
What is the common gesture for touchpad to do it? maybe we can make it work different for osx, more "touch pad friendly" Thing takes place in PanTool.java. which receives events from SandboxMediator.

**Comment by azakhary** [comment]
How about 2 finger tap and drag? we can count points on drag event.

**Comment by jymen** [comment]
Ok thanks I'll look at it today and let you know

**Comment by jymen** [comment]
On Mac the 'SpaceBar + Drag' works well for moving camera.
This gesture is also consistent either with apple intellimouse or touchpad ... although I find dragging with touchpad  usually not practical ... But Anyway as I said before it's consistent with intellimouse and usually designers are more using mouse than touchpad
