### ISSUE TITLE
Position, Height and Width properties get weird behavior

### ISSUE THREAD

**Issue by cdxcxn** [UnderwaterApps/overlap2d#106]
Everytime I select an object, this properties are marked as error in the editor (Red) and I need to rewrite every value. The error it's for the comma ( , ) that the editor puts automatically before puts a correct value. The correct behavior must be like Rotation, Scale properties.

![properteis_bug](https://cloud.githubusercontent.com/assets/13453194/8827648/85346b7a-3053-11e5-9dd0-1da1b3a71ad1.png)

**Comment by cdxcxn** [comment]
Already posted by azakhary as a bug in
https://github.com/UnderwaterApps/overlap2d/issues/109

**Comment by azakhary** [comment]
Oh, sorry, didn't see you posted it :D My bad. As this one is closed, let's keep the other one. Again, thanks for reporting :)

**Comment by cdxcxn** [comment]
Np dude, thanks to you!
