### ISSUE TITLE
Camera position not saved in project 

### ISSUE THREAD

**Issue by jymen** [UnderwaterApps/overlap2d#107]
I think saving the camera current position for a given project and of course using this last saved position when project is opened again would be a good idea

**Comment by azakhary** [comment]
Had the same thought yesterday, makes sense. I agree to saving that data. It can go to the same place we save ruler position's per scene.

**Comment by jymen** [comment]
I agree saving rulers positions also is a good point

**Comment by azakhary** [comment]
implemented in #113
