### ISSUE TITLE
Scroll zoom

### ISSUE THREAD

**Issue by tomiit123** [UnderwaterApps/overlap2d#117]
As I am using Photoshop and illustrator for creating images it would be useful to make scrollable zoom with CTRL+Mouse Scroll and it will be zoom in or zoom out the workspace and it will be also changing immediately exact percentage value in Zoom values.
For examle right now is there 100% and when I CTRL+Mouse Scroll to zoom in it change to for example 112%.
It improve work with workspace.

Tomas.

**Comment by azakhary** [comment]
Makes sense, but I wanted to add, not sure if you already know this or not, but you can zoom in/out with Ctrl- or Cltr+ As in photoshop. Although it doesnot update the value of zoom in percent box.

**Comment by Mattier** [comment]
+1

I love the fact that we can zoom now, but this enhanced functionality will really help with productivity even more. Most art programs use this feature, and I know that my art team would appreciate it.When they are primarily working with the mouse, it can be annoying to have to switch to two hands on the keyboard every time they have to zoom, which is A LOT. xD

**Comment by azakhary** [comment]
Let me see if I can do it in near 10 mins :)))

**Comment by azakhary** [comment]
Done in #135

**Comment by azakhary** [comment]
So it took 8 minutes not 10 :-P you  can download latest build from the main page "Latest Build" button.
