### ISSUE TITLE
[Bug] Unable to scale rotated objects using handles

### ISSUE THREAD

**Issue by spaceemotion** [UnderwaterApps/overlap2d#12]
_Disclaimer: This is actually just an assumption, I haven't quite tested a newer overlap2d version out yet (I was using the one from a week ago)._

While I was using Overlap2D I noticed that I was unable to use the resize handles on objects when they were rotated.

**Recreation:**
1. Create a new object
2. Resize the object by at least 10 degrees
3. Go into resize mode
4. Try to resize the object with the handles

Other than that, awesome product, keep it up!

**Comment by azakhary** [comment]
Yep, that is an existing issue, let me look into it, I'll update as I have more info.

**Comment by azakhary** [comment]
Just to mention this is still a bug in #75

**Comment by Sasun** [comment]
issue fixed
