### ISSUE TITLE
Build fails (Spine dependency issue)

### ISSUE THREAD

**Issue by butaca** [UnderwaterApps/overlap2d#13]
Just cloned the repos and the gradle build fails with the following errors (it seems to be an issue with Spine):

src/com/uwsoft/editor/gdx/sandbox/ItemFactory.java:158: error: cannot find symbol
        itm.setAnimation(itm.skeletonData.getAnimations().get(0).getName());
                            ^
  symbol:   variable skeletonData
  location: variable itm of type SpineActor
com/uwsoft/editor/gdx/ui/properties/SpineAnimationProperties.java:46: error: incompatible types: Object cannot be converted to Animation
        for (Animation animation : object.getAnimations()) {
                                                       ^
com/uwsoft/editor/gdx/ui/properties/SpineAnimationProperties.java:58: error: incompatible types: Object cannot be converted to Animation
        for (Animation animation : ((SpineActor) item).getAnimations()) {
                                                                    ^
com/uwsoft/editor/gdx/ui/thumbnailbox/SpineAnimationThumbnailBox.java:72: error: cannot find symbol
        animThumb.setAnimation(animThumb.skeletonData.getAnimations().get(0).getName());
                                        ^
  symbol:   variable skeletonData
  location: variable animThumb of type SpineActor

**Comment by azakhary** [comment]
Have you gone through the steps in README.md setting up part?

**Comment by azakhary** [comment]
You need to do this:

Overlap2D requires for it to be in same folder in which o2d and spine runtimes are located so you need to clone them separately
Clone overlap2d-runtime from here
Clone spine runtimes from here
Make sure that paths are correct by taking a look (not modifying) settigs.gradle of overlap2d project

Before gradle import.

**Comment by butaca** [comment]
Yes, I read the docs first. Maybe I'm missing something. I cloned the repos
in the following structure:

[ProjectsFolder]/overlap2d/
[ProjectsFolder]/overlap2d-runtime-libgdx/
[ProjectsFolder]/spine-runtimes/

Then proceded with the gradle build.

Am I missing something?

Thanks.


On Thu, Apr 2, 2015 at 2:37 PM, Avetis <notifications@github.com> wrote:

> You need to do this:
>
> Overlap2D requires for it to be in same folder in which o2d and spine
> runtimes are located so you need to clone them separately
> Clone overlap2d-runtime from here
> Clone spine runtimes from here
> Make sure that paths are correct by taking a look (not modifying)
> settigs.gradle of overlap2d project
>
> Before gradle import.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UnderwaterApps/overlap2d/issues/13#issuecomment-88984314>
> .
>



-- 
Saludos,
Juan

**Comment by choxxy** [comment]
Yep having the same error 'skeletonData' cannot be resolved. Have check SpineActor class its not defined??

**Comment by azakhary** [comment]
hmm. let me think. 
so spine-runtimes folder contains this correct: spine-runtimes/spine-libgdx/spine-libgdx ?
And you clean/refreshed gradle?

I'll try to check this out, will get back to you when I figure it out.

**Comment by azakhary** [comment]
okay I am stupid.

**Comment by azakhary** [comment]
Also can you try switching overlap2d runtime to dev branch, while I am on it?

**Comment by butaca** [comment]
Switching overlap2d-runtime-libgdx to dev branch worked. Thanks.

On Thu, Apr 2, 2015 at 3:05 PM, Avetis <notifications@github.com> wrote:

> Also can you try switching overlap2d runtime to dev branch, while I am on
> it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UnderwaterApps/overlap2d/issues/13#issuecomment-88994713>
> .
>



-- 
Saludos,
Juan

**Comment by azakhary** [comment]
Just added that to the README.md my bad... Sometimes I forget simple things..

Thank you guys for tracking this, and sorry for confusion.

**Comment by butaca** [comment]
Thanks to you for sharing this amazing work. :)

El jueves, 2 de abril de 2015, Avetis <notifications@github.com> escribió:

> Just added that to the README.md my bad... Sometimes I forget simple
> things..
>
> Thank you guys for tracking this, and sorry for confusion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UnderwaterApps/overlap2d/issues/13#issuecomment-88998358>
> .
>


-- 
Saludos,
Juan

**Comment by robcowell** [comment]
Still getting this dependency issue I'm afraid, even with the runtime on the dev branch....
![screen shot 2015-04-02 at 21 33 38](https://cloud.githubusercontent.com/assets/2143167/6973082/20fb4e64-d980-11e4-971d-dc60fc825252.png)

**Comment by azakhary** [comment]
tried doing gradle refresh?

**Comment by robcowell** [comment]
From Eclipse, right-clicked the project, and did Gradle->Refresh All on all 3 projects. Spine runtimes first, then overlap2d libgdx runtimes, then overlap2d.  Still the same I'm afraid

**Comment by butaca** [comment]
You shoud run the gradle task clean.

On Thu, Apr 2, 2015 at 5:50 PM, Rob Cowell <notifications@github.com> wrote:

> From Eclipse, right-clicked the project, and did Gradle->Refresh All on
> all 3 projects. Spine runtimes first, then overlap2d libgdx runtimes, then
> overlap2d. Still the same I'm afraid
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UnderwaterApps/overlap2d/issues/13#issuecomment-89041537>
> .
>



-- 
Saludos,
Juan

**Comment by azakhary** [comment]
Does running "clean" task helped ? I have added more info in readme, so I am closing this issue for now.
