### ISSUE TITLE
Box2d Physics has not effect at runtime.

### ISSUE THREAD

**Issue by PkayJava** [UnderwaterApps/overlap2d#136]
at runtime, SceneLoader.world is always null,

**Comment by azakhary** [comment]
That is very true. Data is there, but system is not. Basically runtime will officially support physics in a week. I am on it.

**Comment by artemlive** [comment]
azakhary, is there any news about this issue? Thanks for any information.

**Comment by azakhary** [comment]
this is now fixed

**Comment by artemlive** [comment]
Great, thank you!
