### ISSUE TITLE
Item physics editor window culling

### ISSUE THREAD

**Issue by Estevo-Aleixo** [UnderwaterApps/overlap2d#14]
The item physics editor does not remove the texture outside of the view.

Alpha v0.0.7

http://i.imgur.com/PlcU50S.png

**Comment by azakhary** [comment]
Will take a look during weekend.

**Comment by RgehanProjects** [comment]
It only does that on images. CompositeItems don't seem to be affected.

**Comment by azakhary** [comment]
This is now irrelevant, as starting from #75 there is no physics editor dialog, it is integrated with main scene. So I am marking as fixed.
