### ISSUE TITLE
change on color picker is applied even though dialog is canceled

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#150]
to reproduce:
1- open color picker dialog (for an item's tint)
2- replace the color hex value by copy/paste or just typing in (another color value)
3- click on the cancel button

**Comment by htynkn** [comment]
I think this issue is fixed.

**Comment by kutoman** [comment]
the issue might be fixed in VisUI, but it's not applied to o2d yet. I guess we need the snapshot version of VisUI ?

**Comment by azakhary** [comment]
I agree to update to a newer VisUI version, but not a snapshot. as they break things a lot, that happened before.

**Comment by kutoman** [comment]
fixed now
