### ISSUE TITLE
Composite recalculates it's size wrong when items are rotated

### ISSUE THREAD

**Issue by azakhary** [UnderwaterApps/overlap2d#165]

**Comment by saltares** [comment]
Is this related to the editor? In the editor, the only thing I found is that you need to click the composite item for the boundingbox to be updated after a rotation.

![wrong rotation](https://cloud.githubusercontent.com/assets/570314/10715685/1c75dcea-7b17-11e5-97f1-adce7add3d7e.PNG)

**Comment by azakhary** [comment]
not only, we had issues with composite recalculation not taking in account transformations, which I think @gevorg-kopalyan have gixed, but I am not sure if he have made a PR. @gevorg-kopalyan  can you confirm?

**Comment by gevorg-kopalyan** [comment]
Yeah the fix with transforms is there, but as David mentioned, it only updates Follower box on click, which is an issue on Follower part I guess.

**Comment by azakhary** [comment]
Ah right, I remember now. So the issue is a bit more complex. There are more scenarios this can go bad.
of course the classic one is, Basic follower should probably also listen for item updated notification to update itself in that case as well. (I mean the Followers mediator should do it, and call updates on item update) which as far as I remember it should do, so maybe it bugs there.
 
But besides that. 
The basic follower class that uses dimension component to know size of item, and it put's rectangle starting from x, y + dimensions multiplied by scale. now this is not always right, for example when things are on minus coordinates of composite, it will not be included in rectangle, unless we shift them all. And also basic follower should behave differently when it's a polygon. But that's totally another topic.

**Comment by azakhary** [comment]
So this, FollowersUIMediator.java   listens to ITEM_DATA_UPDATED which is fine. Now somehow I guess when you edit composite and go up, this does not happen beacause while you are inside composite the follower for parent composite doesnot yet exist, and when you go one step up it auto sets, if I remember correctly, maybe somewhere there it should update. I am not sure in exact steps to reproduce, but I hope this helps.

**Comment by InnerScript** [comment]
@azakhary 

I'm working on fixing similar issues with polygon editing. (this might get fixed along the way, too)

I was hoping you could share with me where the transform and dimensions components are rendered. Also, for polygons (basic primitives) where the color fill is rendered (currently I have the outlines working, but the color fill sometimes detaches)

**Comment by azakhary** [comment]
well the components don't get "rendered" what happens is, each item type, has it's own "Draw" logic:
https://github.com/UnderwaterApps/overlap2d-runtime-libgdx/tree/master/src/com/uwsoft/editor/renderer/systems/render/logic

the polygon's are currently just a modifiers of simple images, so thei get rendered in textureregion rendering logic at this moment. Each render logic can take any component from the mappers in order to know what and how to render.

**Comment by Sasun** [comment]
issues fixed
