### ISSUE TITLE
Gradle fail to compile on some o2d files

### ISSUE THREAD

**Issue by whitegfx** [UnderwaterApps/overlap2d#17]
Hi spine and libgdx gradle projects was compiled, but not overlap2d prj. Fail on methods that calls some props on spine runtime during compilation overlap2d.

Is the current spine runtime compatible with current overlap2d dev sources? Let me know.

dev stack:
osx 10.9.5
jdk 1.8
eclipse: 4.2.x

overlap2d/src/com/uwsoft/editor/gdx/sandbox/ItemFactory.java:158: error: cannot find symbol
        itm.setAnimation(itm.skeletonData.getAnimations().get(0).getName());
overlap2d/src/com/uwsoft/editor/gdx/ui/properties/SpineAnimationProperties.java:46: error: incompatible types: Object cannot be converted to Animation
        for (Animation animation : object.getAnimations()) {
overlap2d/src/com/uwsoft/editor/gdx/ui/properties/SpineAnimationProperties.java:58: error: incompatible types: Object cannot be converted to Animation
        for (Animation animation : ((SpineActor) item).getAnimations()) {
overlap2d/src/com/uwsoft/editor/gdx/ui/thumbnailbox/SpineAnimationThumbnailBox.java:72: error: cannot find symbol
        animThumb.setAnimation(animThumb.skeletonData.getAnimations().get(0).getName());

**Comment by azakhary** [comment]
Have you switched overlap2d runtime to "dev" branch?

**Comment by azakhary** [comment]
If it does not work, try to running gralde "clean" task, and try again. 
overlap2d master branch is made for simple use and does not expect spine runtime. dev branch is made to use with the editor.

**Comment by whitegfx** [comment]
Switching to dev branch and o2d running. I read read me but forgot to switch ;) thx
