### ISSUE TITLE
Editor crash when add physic component

### ISSUE THREAD

**Issue by PkayJava** [UnderwaterApps/overlap2d#170]
something wrong with PhysicsBodyLoader.createBody, it has problem with SCALE,

verts x and y value is too small,

Step to reproduce : create new project with 
 Pixel per WU : 80
 Resolution 720w x 1280h

I am not sure why do we need to SCALE = 10f/Gdx.graphics.getWidth(),

I tried SCALE = 1f, it works fine, but I am not sure it will mess up the coordination of the game or not,

**Comment by azakhary** [comment]
That's a bummer, it appears scale was not depending on pixel per world. Fixed.
