### ISSUE TITLE
Text change not affecting label item?

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#172]
![unbenannt](https://cloud.githubusercontent.com/assets/5825645/9150688/2c7410e2-3de8-11e5-8d51-ebae1b772c1c.png)

**Comment by azakhary** [comment]
It somehow only changes when you press enter, or when yor focus out. I think we need to have a more custom listener for text field that fires on any text change. That's an old issue. But yes has to be fixed.

**Comment by azakhary** [comment]
Currently it uses standard input field KeyboardListener, can have another one similar but a bit different.

**Comment by kutoman** [comment]
even enter (it's puttin a line break) or focus out don't work.

**Comment by kutoman** [comment]
should I take this task?

**Comment by azakhary** [comment]
yesplease ^^

**Comment by kutoman** [comment]
while implementing I realized that a label data update can't be undone currently. Should every typed char be undoable? Or how would you manage that?

**Comment by azakhary** [comment]
well it should be similar to how "move command is done" when you move item around it's actual values get changed. but when you do mouse up. it fires the command that kinda provides both current and previous (pre-move) position. Same should be with label text. when you type actual values should change, before you start typing a backup should be remembered. when you focouse out. it should fire the command providing both current and prev values so action will be undoable.  Does that make sense?

**Comment by kutoman** [comment]
yes it does :)

**Comment by kutoman** [comment]
As I was trying to figure out how item properties mediation works, I noticed that the Text tool itself has some bugs. When I choose the text tool and put a new Label item on the canvas, the properties view does not show all label specific properties (I guess it should?).. And when I rechoose the text tool, then all label specific properties are shown (e.g. font size etc.), but this time there is no link of these properties to the new label item I will put on canvas.
![labelitemissue](https://cloud.githubusercontent.com/assets/5825645/9155628/bda5f596-3ebd-11e5-95ea-264b34ae5573.png)

**Comment by azakhary** [comment]
Hm, I think it's just scrolling issue, if you click on it and scroll they will appear. it just isn't resizing.

**Comment by kutoman** [comment]
ah I see, didn't know that the box contents are scrollable oO. thx

**Comment by kutoman** [comment]
at least a scrollbar for indication would make sense

**Comment by azakhary** [comment]
there is a scroll bar, but it only shows well.. when you scroll. I was thinking on having it "always there" but currently it looks ugly because of it's positioning over the things. if we change it to move a bit right, maybe keeping it always there will be good.

**Comment by azakhary** [comment]
So I assume we can mark this one as fixed by @kutoman
