### ISSUE TITLE
Editor Plugin

### ISSUE THREAD

**Issue by PkayJava** [UnderwaterApps/overlap2d#173]
in the moment plugin have to be in directory "plugins", which is correct.

I have difficulty of compiling and debugging,

I would like to modify BootstrapPlugins, to looking for pluggin which are implement inside the editor project itself either. It works great,

I added the following code 

        {
            Collection<Module> loadedPlugins = manager.loadModules(new File(ClassLoader.getSystemResource(".").getPath()));

            System.out.println(loadedPlugins.size());
            for (Module module : loadedPlugins) {
                try {
                    pluginManager.initPlugin((O2DPlugin) module.getClass().newInstance());
                } catch (InstantiationException e) {
                    e.printStackTrace();
                } catch (IllegalAccessException e) {
                    e.printStackTrace();
                }
            }
        }

If you are okay with that I will commit, and do a pull request.

**Comment by azakhary** [comment]
The way I debug plugins is, just make your plugins gradle "jar" task to build jar in the correct location. That way it will be super fast to debug. You will be able to build, and then quickly run.

I just do not see other practical use for using other editors inner folder, other then debugging, which is solvable the way I mentioned.

**Comment by azakhary** [comment]
Or you can temporary make this change, to debug the plugin, but then stash it.

**Comment by PkayJava** [comment]
okay I won't commit, just keep locally then !

**Comment by azakhary** [comment]
Btw, what plugin are you making? :-P
