### ISSUE TITLE
o2d-runtime problem with box2d world.QueryAABB

### ISSUE THREAD

**Issue by PkayJava** [UnderwaterApps/overlap2d#175]
step to reproduce : 

    @Override
    public void create() {
        this.camera = new OrthographicCamera();
        this.viewport = new FitViewport(9, 16, camera);
        this.loader = new SceneLoader();
        this.loader.loadScene("MainScene", this.viewport);
        this.world = this.loader.world;
    }

    @Override
    public boolean touchDown(int screenX, int screenY, int pointer, int button) {
        this.touchedPoint.x = screenX;
        this.touchedPoint.y = screenY;
        this.touchedPoint.z = 0;
        this.camera.unproject(this.touchedPoint);

        this.world.QueryAABB(this.callback, this.touchedPoint.x, this.touchedPoint.y, this.touchedPoint.x, this.touchedPoint.y);

        return false;
    }

ray reportFixture method is not called, I checked this.touchedPoint, it is unproject correctly.
but I don't know why ray reportFixture is not called.

**Comment by azakhary** [comment]
Do you take into account "scale" value? viewport is not 1 to 1 to the physics world. So you have to multiply (or devide by scale) and scale value is obtainable from PhysicsBodyLoader.getScale();

**Comment by PkayJava** [comment]
oh yeah, you are right,
