### ISSUE TITLE
o2d-runtime box2d position alway 0,0 when game start

### ISSUE THREAD

**Issue by PkayJava** [UnderwaterApps/overlap2d#176]
when first start, entity always show at position 0x0
if I remove physic component then it show in the correct position 1.88x2.11

{
			"uniqueId": 3,
			"itemIdentifier": "test",
			"tags": [],
			"x": 1.88,
			"y": 2.11,
			"originX": 0,
			"originY": 0,
			"layerName": "Default",
			"shape": {
				"polygons": [
					[
						{},
						{
							"y": 3.03
						},
						{
							"x": 2.36,
							"y": 3.03
						},
						{
							"x": 2.36
						}
					]
				]
			},
			"physics": {
				"mass": 1,
				"allowSleep": true,
				"awake": true,
				"density": 1,
				"friction": 1,
				"restitution": 1
			},
			"imageName": "blue"
		}

**Comment by PkayJava** [comment]
I found the problem now, when create physic body object first time, it does not take TransformComponent, that why it always stay at 0,0

PhysicsBodyLoader.createBody this method should take param TransformComponent, what do you think ?

**Comment by azakhary** [comment]
instead of taking transform component. the system that calls create body method. can immediately after the call, position body according the the transform component.

**Comment by azakhary** [comment]
I fixed it. It's in latest snapshot!

**Comment by azakhary** [comment]
Thanks a lot for reporting this.
