### ISSUE TITLE
UserData of box2d body data should be Entity itself

### ISSUE THREAD

**Issue by PkayJava** [UnderwaterApps/overlap2d#183]
after ray cast or query aabb, box2d object is found, and we want to remove its entity from engine, I think it should be good, to setUserData(entity), what do you think ?

**Comment by azakhary** [comment]
Oh I haven't thought about that. So am I getting this right. You are talking about retrieving the entity from the body? Yeah could be good idea. makes sense.

**Comment by PkayJava** [comment]
yeah

**Comment by azakhary** [comment]
Thanks, just merged!
