### ISSUE TITLE
Implement AsynchronousAssetLoader for ResourceManager

### ISSUE THREAD

**Issue by PkayJava** [UnderwaterApps/overlap2d#187]
what do you think, if we have an AsynchronousAssetLoader for ResourceManager, it will be useful for make loading screen.

**Comment by azakhary** [comment]
I do have one made somewhere, for my use

**Comment by azakhary** [comment]
But I am not sure if that has to be bundled with the runtime. want to keep runtime light.

**Comment by PkayJava** [comment]
i am happy to implement a small one for that, I will ask for merge back, if it is was finished, what do you think ?

**Comment by azakhary** [comment]
would be awesome if you can provide a simple one! mine was just a little bit custom.

**Comment by PkayJava** [comment]
I checked, ResourceManager.skeletonAtlases, it is always empty, is it a right one ? I think it should file with this folder sprite_animations, am i correct ?

**Comment by PkayJava** [comment]
I have just request a merge at o2d-runtime

**Comment by azakhary** [comment]
Can we call it AsyncResorceManager ?

**Comment by PkayJava** [comment]
Sure

**Comment by PkayJava** [comment]
I just recommited,

**Comment by azakhary** [comment]
Awesome, thanks! I'll merge it first thing tomorrow morning, can't do right now :)

**Comment by azakhary** [comment]
merged. thanks!
