### ISSUE TITLE
renaming layer which already contains some items leads to inconsistency

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#189]
if I rename a layer which already has some items, the VOs (layer name reference) of those items don't get adapted. I noticed that when building the root composite actor of that scene.

**Comment by azakhary** [comment]
What are the consequences of that?

**Comment by kutoman** [comment]
I get a NullpointerException when creating a CompositeActor, since the given layer name does not exist anymore in the layer map.

**Comment by azakhary** [comment]
I see. I'll fix this one.
