### ISSUE TITLE
File Menu, remember last project/s locations

### ISSUE THREAD

**Issue by whitegfx** [UnderwaterApps/overlap2d#19]
o2d project is somewhere in hd and every time when I need to open it I must select full path again and again ;) Last opened will be fine.

osx 10.9.5, jdk 1.8, eclipse: 4.2.x, build from sources

**Comment by eumario** [comment]
Looking to add this feature currently.

**Comment by azakhary** [comment]
We can use gdx preferences to save editor specific data.

**Comment by eumario** [comment]
I'm working on creating a Preference Manager (Using Gdx.Preferences), and setting up the History of Recent Projects, to be displayed under the file menu.  Should have something done in the next 2 or 3 days.

**Comment by eumario** [comment]
This is actually closed with my patch: 992378aa6728904fce2cbe4d184779c417dc0219, which adds the Recent Projects... menu item to the File Menu.  @whitegfx Let me know if that will work for you.

**Comment by whitegfx** [comment]
Great I will try it.

12. 4. 2015 v 23:23, eumario <notifications@github.com>:
