### ISSUE TITLE
(enhancement) plans on extensions for actors other than CompositeActor?

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#197]
I'm curious what your plans are for supporting methods like getTags() or getCustomVars on all actors, used in overlap2d.

**Comment by azakhary** [comment]
well, my plans are like this:

if you need it, I'll do it.

**Comment by kutoman** [comment]
I like that :D.. well at least I could need it on actors like Label, Image etc.. I think it's better than having to put a CompositeActor on those actors in order to retrieve the tags or custom vars.

**Comment by azakhary** [comment]
oh wait, if you mean to have that on all actors, I am not sure how that's possible. we are using simple libGDX actors that we cannot modify :) whatever happen should happen through CompositeActor.

I would go further, and say, my plans are - make the entity mechanism so good for UI as well, that at some point, everyone will decide not to use Actors. but, while it's far away, I have to support both. Although as you can see using actors will come with it's issues.

**Comment by kutoman** [comment]
ok I see :)
