### ISSUE TITLE
[enhancement] CompositeActor method to insert/add a new item

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#198]
the `Group` superclass does provide a method do add an actor, yet it's not possible to add an item with an id and assigned layer name. Why that? For example, when I want to support text field actors in overlap2d, I first put some textfield placeholders in the scene. But those placeholders might have certain ids (which I would like to hand over to the replacing textfield) and might also be assigned to certain layers (which in some cases are relevant). Currently I can't do that.

**Comment by azakhary** [comment]
we can override addActor, or rather create another method with that name but different params, receiving, vo, on the input or something) Although, it would be of big help if you bring up a real life scenatio why it's needed. The reason I ask, I do not want CompositeActor to be big and used that much honestly. It's the last resort, when you really need actors. but I personally, will do everything to not use it at all, and even try to make up my UI using the conventional entity engine.

**Comment by kutoman** [comment]
the reason why I insist on the actors is, that my game does not require the entity system (it's a quiz game). It would be kinda overkill. Thus, as I work with overlap2d's runtime, I also work on utility functionality for the runtime's scene2d handling, to make the development more convenient. One scenario is, that I want to automatically replace placeholders (since there are actors like `TextFields` which are not supported directly by overlap2d) of my scenes which have certain tags. But my replacing mechanism also have to hand over the meta data (id, tags, custom vars) of the placeholders to the real actors. If the replacement was done properly as described I would have the possibility to retrieve the new "real" actors just by calling the root composite actors `getItem(id)` method, since the id already got assigned to the new actor. In addition to that that new actor also would get affected by `setLayerVisibility` as it was assigned to a certain layer.

**Comment by azakhary** [comment]
I wouldn't say entity system is overkill. It might lag more if you use actors for everything.
But, I see your point. we shall make the improvements at once!

**Comment by kutoman** [comment]
I already consider to use the entity framework for another project, as I kinda like that architecture even though it would be my first time :)

**Comment by azakhary** [comment]
I am new to it too. Although already love it.

**Comment by kutoman** [comment]
this can be also closed, as it is now possible to do so
