### ISSUE TITLE
Renaming identifier (image or group) delete object

### ISSUE THREAD

**Issue by whitegfx** [UnderwaterApps/overlap2d#20]
1. set identifier name on image or group
2. save scene
3. try to rename it using (backspace or delete key)
4. object wil be removed from scene and from scene tree

osx 10.9.5, jdk 1.8, eclipse: 4.2.x, build from sources

**Comment by azakhary** [comment]
I'll look into this one.

**Comment by whitegfx** [comment]
Great. Also other things react in the similar way:
Deleting using backspace PosX,Y in object pros (remove obj). CMD+C, CMD+V in PosY, will duplicate object, but not posx number for pasting...

**Comment by azakhary** [comment]
Fixed as per #32
