### ISSUE TITLE
[enhancement] link Label item's tint property with its fontColor?

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#200]
Since currently the tint color has no visual effect on a label, I would suggest to consider it as the font's color? (accordingly might also make sense for the scale values?)

**Comment by azakhary** [comment]
I think that makes sense. No reason to use 2 colors and confuse things more.

**Comment by kutoman** [comment]
ok, may I take this task?

**Comment by azakhary** [comment]
Sure! Although please consider that it goes deep in runtime, to the label draw logic class, as well as some of the components, systems and UI panels with their mediators.

**Comment by kutoman** [comment]
I only modified the draw logic class for this, not sure why you mentioned the other parts

**Comment by azakhary** [comment]
right. my bad.
