### ISSUE TITLE
less scene2d more Ashley

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#203]
I just got the idea, to minimize the overlap2d's scene2d part just by using `Actor`'s `setUserObject`/`getUserObject`. You could put the related Entity (or the entity id) as user object. Therefore, we would have the benefit to use Component data for all Actor's (since we know the related entity now and we can benefit from the entity framework to retrieve meta data like id/tags etc) and you don't even have to extend or maintain the runtime's scene2d part anymore. Does it make sense?

**Comment by azakhary** [comment]
The general idea is good.  but there are some issues. It's bad to have some kind of fake entities put inside an actor, as I am not  even sure this will work. if entities are not in the engine. plus this is to artificial. But, the general idea is good. we can have some kind of "essential important data" type of thingie, with tags and all, and we can have that as object assign by setUserObject to all the actors. That would be cool.

**Comment by kutoman** [comment]
right, I see your point. I'm going to work on this, ok?

**Comment by azakhary** [comment]
That would be cool! I assume this is something you need a lot for your UI.

**Comment by azakhary** [comment]
if you can provide some slight info on the architecture of this, so we can discuss before you dive deep in, that would be awesome. To avoid double re-doing.

**Comment by kutoman** [comment]
that's true :D, ok I will

**Comment by kutoman** [comment]
first I think about creating a new class which will be used as user object for each item:
```
public class CommonItemVO {
    public String id = null;
    public String[] tags = null;
    public int layerIndex = 0;
    public Map<String, String> customVars = null;
}
```

**Comment by kutoman** [comment]
the members of `CompositeActor` will also be modified.
As some maps wouldn't need to get maintained anymore (e.g. itemMap, itemLayerMap) because now the children have the necessary meta data. Therefore the methods like `getItem(id)` etc would change slightly.

**Comment by azakhary** [comment]
VO's are for classes that read JSON. let's name it CoreData
rest makes sense.

**Comment by azakhary** [comment]
or CoreActorData to make clear it's for actors

**Comment by kutoman** [comment]
oh ok. Besides, do I miss something else? I think that's it.

**Comment by azakhary** [comment]
I think that would be convenient to keep CustomVars object in it, that is loaded with customVars string, because it will make faster reading of custom vars. Also maybe some helper methods. I think you will do this the best, as you are doing a project using this part, and you will see exactly which helper methods are needed.

**Comment by kutoman** [comment]
ok I will extend it by helper functions during progress, later on.

**Comment by kutoman** [comment]
I guess close for now?

**Comment by azakhary** [comment]
yep
