### ISSUE TITLE
overlap2d's drawing system messed up?

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#212]
this is what I get now with the latest commits, when I switch from one scene to another scene (might be still the same scene). The previously drawn scene also gets drawn.
![unbenannt](https://cloud.githubusercontent.com/assets/5825645/9466570/0460b820-4b36-11e5-8542-214cf1f3a270.png)

**Comment by azakhary** [comment]
oh... I .. my bad.. I'll fix it.

**Comment by azakhary** [comment]
Pushed to latest runtime.
