### ISSUE TITLE
Crash after Composite conversion

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#213]
Again one bug concerning this, I thought that I fixed that :(
to reproduce:
1- create new layer with a name other than "Default"
2- convert any item to a composite on that new layer
3- enter that composite item
4- click on the canvas

**Comment by azakhary** [comment]
That's actually a new one, I had it worse, yesterday, load scene where is composite, enter composite (it has 2 images) delete one. it crashes. It does not crash though if I "cut" it. This is new bug, not sure how it happened. :s And might be related to your issue as well. have to take a look, but I cannot today :(((

**Comment by kutoman** [comment]
hmm I couldn't reproduce it. It maybe got fixed

**Comment by azakhary** [comment]
Got it, I'll keep an eye on it
