### ISSUE TITLE
Is there any json format documentation?

### ISSUE THREAD

**Issue by Roger** [UnderwaterApps/overlap2d#225]
I want to make a runtime for http://luxeengine.com/ and didn't found docs about json format, is there any  or just the runtime as reference?

**Comment by azakhary** [comment]
Hi Roger, there is no docs for that (my bad) but. TI's pretty easy to "read" : 

https://github.com/UnderwaterApps/overlap2d-runtime-libgdx/blob/master/src/com/uwsoft/editor/renderer/data/SceneVO.java

ignore methods and just look at fields, they use other VO, take a look at their fields, and that is the exact structure of JSON.

I am not sure how to make the docs, will just a pretty printed JSON with some comments do? I can do that.

I would love to see o2d on luxengine, a  solid runtime would be nice. or if you guys have your own format for data as well, we can have an additional plugin for o2d (we do have oepn plugin API)

So all and all - I am very interested in extending to new engines, so tell me how can I help, and I will try to provide maximum support.

**Comment by Roger** [comment]
Thanks for the fast response!
I guess a pretty printed JSON with some comments should do.
I'll push any advance on this, thanks for the directions =).

**Comment by azakhary** [comment]
okay, will try to get you a pretty print JSON in near 2 days

**Comment by htynkn** [comment]
+1 
If we have json format documentation, then we can use overlap2d as a normal toolkit for UI and Level design, not just for libgdx.
Also the document can help others easily to create runtimes for other platforms.

**Comment by azakhary** [comment]
Hey guys, enjoy:
http://overlap2d.com/data-api-creating-custom-runtime/

Let me know if there it's still not a clear doc.

**Comment by Roger** [comment]
@azakhary thanks! another question, what is the format of the image atlas?

**Comment by Roger** [comment]
found that is from the libgdx packer and here is the reader, https://github.com/libgdx/libgdx/blob/fa21bbd665de1d25f326bc0f78acc862e6ca2a7b/gdx/src/com/badlogic/gdx/graphics/g2d/TextureAtlas.java#L102

**Comment by azakhary** [comment]
Yep, that's the thing :)

**Comment by azakhary** [comment]
I am not sure if there is any worldwide standard for atlas files though. But we save in this format.

**Comment by azakhary** [comment]
So I guess I am closing this issue as resolved, because now we have format documentation! Ave me!
