### ISSUE TITLE
Texture bleeding

### ISSUE THREAD

**Issue by chancezeus** [UnderwaterApps/overlap2d#226]
I'm currently working on a game where the camera follows the player (player stays centered). At the moment everything works fine except one small glitch, the background images sometimes show the background around the edges... Looking around I found that the most likely cause is texture bleeding. A simple solution for this is to add edge padding when creating the texture atlas (duplicatePadding = true in the settings) and have a minimum padding of 2... This would duplicate the pixels of the edge into the padding area when packing and solves any rounding errors while rendering...

**Comment by azakhary** [comment]
I see. that actually adds up to a "texture packer" configuration dialog that we need anyway. but that's not a quickie to do. Unless someone really wants to contribute that this week

**Comment by chancezeus** [comment]
I think for a quick fix it should be possible to add it to the default export settings currently used, since it shouldn't break anything (the texturepacker/atlasreader should already be able to handle this, the pixels are actually located in the "unused" padding area, it just happens that the GPU does read them when rounding errors occur).

**Comment by azakhary** [comment]
yeah, if it's just that one field it can be a 1 hour thing to do. I might take a look. but have some other things too

**Comment by chancezeus** [comment]
If you can point me where the textures are packed, I might be able to fix it and PR within the hour...

**Comment by azakhary** [comment]
ExportSettingsDialog.java constructor is where to add new field (padding) has to be on new row, and look decent. ExportSettingsDialogMediator.java saveExportSettings method is the one where you read that data from ExportSettingsDialog and send it with setTexturePackerSizes (add that as a parameter to that method). that is in ProjectManager.java  Now there in that method you see it puts that data to currentProjectVO which is ProjectVO type. So if you add that field called "packPadding" int to ProjectVO it will now be saved automatically to JSON. (Json is serialized from ProjectVO class)
Now that you have functionality to save that data, just make sure it also loads after your reopen thi dialog. or close reopen the project.

Now you have the data you desire in ProjectVO it is the moment of truth:
ResolutionManager.java does the repacking in rePackProjectImages method. you can probably get the data there and pass it to the packer. The only downside here is that we do not re-pack on export. weirdly. so it kinda sux that you have to save that data in export settings. and then, close export dialog. click re-pack button. and then export. But I guess it's ok.

**Comment by azakhary** [comment]
Also just worth checking if same method is called (rePack one) when new image is imported or not. to be on a safe side.
