### ISSUE TITLE
missing package in project?

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#23]
Hi,
I'm trying to compile the project but I suppose something is missing in the repository?

import com.uwsoft.editor.renderer.data.ProjectInfoVO;
import com.uwsoft.editor.renderer.data.ResolutionEntryVO;

does not exist.

**Comment by kutoman** [comment]
oh it's probably from the runtime project?

**Comment by azakhary** [comment]
Yep thats from the runtime project, have you gone through setup instructions in readme file?

**Comment by kutoman** [comment]
sorry for the inconvenience. I recently read the setup steps :D... just ignore this issue
