### ISSUE TITLE
Can I setcolor to one Layer?

### ISSUE THREAD

**Issue by tianqiujie** [UnderwaterApps/overlap2d#234]
Example, I make dialog in dialogLayer. and I make the dialogLayer Translucent? It is very useful

**Comment by azakhary** [comment]
I would not use layer to achieve that though. I mean your entire dialog should be grouped into CompositeActor instead.

I am not sure if we want to add more features that will enable people use layers as groups. because they are not. Layers are for render order simplification.

**Comment by tianqiujie** [comment]
OK, got it
