### ISSUE TITLE
Cannot Delete Resolution

### ISSUE THREAD

**Issue by johanessurya** [UnderwaterApps/overlap2d#236]
I try to change resolution but can't. So I add one and want to delete the old one, but I can't. 

It show dialog box to choose 'Delete' or 'Cancel'. When I click delete. Nothing happen. I tried in other resolution but still can't. I try add new one. So I have 3 resolution and delete it, but can't.

**Comment by azakhary** [comment]
Also adding link t forum post
 http://overlap2d.com/forums/topic/i-cannot-delete-resolution/

**Comment by saltares** [comment]
I think this could be a duplicate of #252.

**Comment by azakhary** [comment]
Yep that's a duplicate, (or rather the other one is). as issue is fixed in #283 PR, I am closing this. And the other one as well, as resolved.
