### ISSUE TITLE
Recent Project List Same Project Over And Over

### ISSUE THREAD

**Issue by johanessurya** [UnderwaterApps/overlap2d#238]
I don't know this is bug or not. 

But I think it's better to submit this issue. 

Take a look at this screenshot: 
![overlap2d-recent-project](https://cloud.githubusercontent.com/assets/2444537/9704147/de3faad6-54c5-11e5-8266-c769a34115f9.jpg)

When I load same project, recent project add new list even it has listed.

**Comment by kutoman** [comment]
this issue is mentioned in #93

**Comment by azakhary** [comment]
yeah it's a duplicate, athough, the issue is, every time I want to fix it, I can't reproduce. I mean I can't figure out at what point it starts saving duplicating project names, is there a scenario to reproduce?

**Comment by johanessurya** [comment]
>is there a scenario to reproduce?

@azakhary When you load project from "Recent Project". Please try load a project from "Recent Project", It would add a project to "Recent Project" list.

**Comment by azakhary** [comment]
Okay, I am taking this one

**Comment by azakhary** [comment]
okay, fixed by cleaning duplicates. issue was in inconsistent slash notation through the paths when project is created versus opened.
