### ISSUE TITLE
[Feature request] Zoom-in/out in editor

### ISSUE THREAD

**Issue by jacktech24** [UnderwaterApps/overlap2d#24]
Hi, I love overlap2d editor, but there is one huge thing missing and that is zooming in/out in the editor, because when I am working with multiple resolutions, it's a huge problem.

**Comment by azakhary** [comment]
I am fully on this, hopefully we will have zoom-ing today :)

**Comment by azakhary** [comment]
Okay, done. You can now zoom and and zoom out using either Alt+MouseScroll or Control/Command And +- keys at this moment there is no indicator of current zoom, or a scrollbar with zoom options. I will add this as another feature, while this one is being tested.
