### ISSUE TITLE
graphics issue

### ISSUE THREAD

**Issue by CoderJoe1999** [UnderwaterApps/overlap2d#241]
not animation objects are blurry causing a grid like appearance when put side by side
![error](https://cloud.githubusercontent.com/assets/14153530/9706809/e551a524-54af-11e5-8464-c8a86c2a4d36.png)

**Comment by azakhary** [comment]
I am not sure I understand. things are in grid because you put them in grid, and nothing is blurry on this pic.

**Comment by CoderJoe1999** [comment]
notice in the picture that there is a grid. I did not put that grid there.
The grid appears because the edges of the images become blurry. The images
themselves are not blurry but when they are imported (or rendered or
something) they become blurry. I will try to attach more photos to better
explain this.

**Comment by CoderJoe1999** [comment]
here is another photo. The blue square guy on the left is an animation. The
blue guy on the right is just one frame imported as an image. But the right
one is blurry. These images are very small (8x10 pixels). I hope this helps.

**Comment by CoderJoe1999** [comment]
![error2](https://cloud.githubusercontent.com/assets/14153530/9826395/307ad3f0-5897-11e5-86d8-907f69c98add.png)

**Comment by CoderJoe1999** [comment]
Figured out the problem. The texture atlas has the filter set to Linear rather than Nearest. Changing this after exporting solved the issue in the runtime but the O2D editor still renders it like that. Maybe there should be a way to set the filter in the editor (which would set the filter in the export as well)?
