### ISSUE TITLE
Font issue in osx

### ISSUE THREAD

**Issue by htynkn** [UnderwaterApps/overlap2d#242]
I try overlap2d in osx 10.10.4  today and I get a null point when I create a text label.

The reason is in `FontManager`, there is no font available.

I notice that in `FontManager` line 67 and 68, the code is commented.

``` java
result[1] = "/Library/Fonts";
result[2] = "/System/Library/Fonts";
```

I check the git log, the code commented with a commit message `osx fixed for fonts`.
They are valid font path for osx, I don't know why we don't use them. 

I uncommented this two lines, it works.

**Comment by azakhary** [comment]
I remember it was crashing for some people as they didn't have this paths or font's in them. it was crashing on startup. I think it should have a solution like: if paths exists load fonts from them, if not don't load fonts from them (do not crash on startup) then when putting label, check if any font isloaded, if list is empty, just don't put label, or alert user that there is no fonts.

**Comment by htynkn** [comment]
If there is no font, overlap2d provides a setting for user to add font?

**Comment by azakhary** [comment]
No, there none. User can add font by adding it to the appropriate folder, and restarting the editor. It will scan that directory on startup. Not user intuitive I know. But take Photoshop for example. There is no setting to add a font. It uses system installed fonts, and if you need new font, you have to add it to the system. same here.
