### ISSUE TITLE
Clean up project layout

### ISSUE THREAD

**Issue by htynkn** [UnderwaterApps/overlap2d#245]
I notice there is one commit 32dfea913d32181a799b687e0dbffe18d1a585c3 to separate project.

For now, the project layout looks strange.
```
-- overlap-common-api
-- src/com/uwsoft/editor
-- test
```
if we try to separate project, the folder should like this
```
-- overlap-common-api
-- overlap
```
Since we are using gradle, could we follow the common practice to use [default project layout](https://docs.gradle.org/current/userguide/java_plugin.html)?

**Comment by azakhary** [comment]
yeah that makes sense. I'll do it tomorrow. The only issue is tests has to be refactored. or no?

**Comment by htynkn** [comment]
I'm not sure. Maybe some test's package name should change.

**Comment by azakhary** [comment]
Will take care of that tomorrow, no worries.

**Comment by azakhary** [comment]
Also I am still thinking if it should be overlap or overlap2d :s

**Comment by azakhary** [comment]
If I put overlap2d stuff in it's own directory, where the test stuff and ylm files should go?

**Comment by htynkn** [comment]
I think each project can have their own tests.

I can see the main project depends overlap-common-api, so if there are some thing need share, we can put it in :overlap-common-api.

**Comment by htynkn** [comment]
One good news is I finally [fix the test stuff](https://travis-ci.org/htynkn/overlap2d/builds/79464115) running in travis. I use docker to provide a envirment to run test. I will create a pull request after you finish this layout change.

**Comment by htynkn** [comment]
How are things going over here?
I want to fix test stuff once this layout change is done.

**Comment by azakhary** [comment]
Hey, I am so sorry for being late. It's just I started doing, it. when I changed layout for some reason it stopped seing runtime, then when I was fixing it my OS died on me, and then I am not event at home now. If you can do something about it - please do. If not. I'll do all of this at monday. Again, sorry. I know you were waiting for me to push the test changes. :(

**Comment by htynkn** [comment]
Hey, no worries. that's ok. And I know we have a dependency which is not in central repo, I believe that private repo is broken.…so the compile is failed because can't download the dependency.

**Comment by azakhary** [comment]
which dependency is that?

**Comment by htynkn** [comment]
the plugin framework. I dont remember the name, start with m. the version is 1.0 snapshot. I ask the owner to publish it to central , but no response. I think you can see detail in gradle error

**Comment by azakhary** [comment]
ouch, that sucks, it was working before.

**Comment by azakhary** [comment]
it's this guys: https://github.com/mountainblade/modular  but they haven't change anything, it was on "snapshot" for a long time. so I am not sure how this can be not working.

**Comment by htynkn** [comment]
Yes, they haven't change anything, but they jar file is on a private repo [http://repo.serkprojects.com/](http://repo.serkprojects.com/) and now that server is 502 error, so we can't download the dependency.

```
* What went wrong:
Could not resolve all dependencies for configuration ':overlap-common-api:compile'.
> Could not resolve net.mountainblade:modular:1.0-SNAPSHOT.
  Required by:
      overlap2d:overlap-common-api:0.1.1
   > Could not resolve net.mountainblade:modular:1.0-SNAPSHOT.
      > Unable to load Maven meta-data from http://repo.serkprojects.com/content/groups/public/net/mountainblade/modular/1.0-SNAPSHOT/maven-metadata.xml.
         > Could not GET 'http://repo.serkprojects.com/content/groups/public/net/mountainblade/modular/1.0-SNAPSHOT/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
   > Could not resolve net.mountainblade:modular:1.0-SNAPSHOT.
      > Unable to load Maven meta-data from http://repo.serkprojects.com/content/groups/public/net/mountainblade/modular/1.0-SNAPSHOT/maven-metadata.xml.
         > Could not GET 'http://repo.serkprojects.com/content/groups/public/net/mountainblade/modular/1.0-SNAPSHOT/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
```

**Comment by htynkn** [comment]
I try to use jitpack to provide the dependency. Take a look at this: 928f6620f5ad3a8f829373c294361c934bbe4c05

It works in travis, see this [log](https://travis-ci.org/htynkn/overlap2d/builds/80055421)

**Comment by azakhary** [comment]
Done #262 
Could you please see if test are fine with new layout? some packages may need refactoring.
+ I fixed the issue with dependency

**Comment by htynkn** [comment]
Cool, leave them to me. I will take a look at test stuff

**Comment by htynkn** [comment]
hmm... I think the layout change has some issue.

I can't run `./gradlew build` in my computer.

Do you try `./gradlew clean build run` after this is done?

**Comment by azakhary** [comment]
weird, I did clean build, works for me

**Comment by htynkn** [comment]
oh... let me delete everything and clone again. it should works.
