### ISSUE TITLE
[Suggestion] Path Project In Title

### ISSUE THREAD

**Issue by johanessurya** [UnderwaterApps/overlap2d#247]
Sometimes I forget where I save my project and I just load it from 'Recent Project'. I would be great if you just print path next to overlap2d title like this:

Overlap2D - [Path Project]

**Comment by azakhary** [comment]
Hmm, yeah that's super easy to do, and I would find it useful as well. will do (unless someone else wants to)

**Comment by azakhary** [comment]
this is being work in progress in #248

**Comment by htynkn** [comment]
I believe this is done. Can we close them?

**Comment by johanessurya** [comment]
Yes
