### ISSUE TITLE
[Bug] Cursor Focus On Wrong Element

### ISSUE THREAD

**Issue by johanessurya** [UnderwaterApps/overlap2d#251]
When "Items Tree" too long. Cursor focus on wrong element.

Here the video that I capture:
https://www.youtube.com/watch?v=L1yFGU58EJ0

**Comment by saltares** [comment]
This issue has already been fixed because the panel has a scrollbar. @azakhary this can now be closed.

**Comment by azakhary** [comment]
Oh, that's an oldie. Yes, this is not relevant anymore.
