### ISSUE TITLE
[bug] Force Close When Delete Resolution And Select It Again

### ISSUE THREAD

**Issue by johanessurya** [UnderwaterApps/overlap2d#252]
I know overlap2d still can't delete resolution that we created.

I just want to try it with new version. Here what I do:
1. Open project named **Tutorial1** 
2. Create a new **Resolution**
3. Delete new one.
4. Select it back.
5. **Force Close**

After that. When I want to re-open **Tutorial1** always force close.

**Comment by saltares** [comment]
On resolution delete, only the assets are deleted, the entry remains in the combobox and the current resolution does not change.

**Comment by azakhary** [comment]
Yep that's a duplicate, (or rather the other one is). as issue is fixed in #283 PR, I am closing this. And the other one as well, as resolved.
