### ISSUE TITLE
Wrong location when creating new project

### ISSUE THREAD

**Issue by azakhary** [UnderwaterApps/overlap2d#266]
How to reproduce:

Create new project located in other then your default o2d directory.
it still get's created in default location.

**Comment by azakhary** [comment]
I am taking on this one.

**Comment by saltares** [comment]
It seems this can now be closed.

**Comment by azakhary** [comment]
Yep. The fix actually caused another mini problem: Now when you fresh download overlap2d with no .prefs the workspace default location in dialog is empty instead of being default location. But that's not a biggie, and can be fixed separately. This one can be closed.
