### ISSUE TITLE
change of tint color in a clone composite item not affecting original item

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#273]
is this intended?

**Comment by azakhary** [comment]
does it matter clone or no clone? If I am not mistaken at this moment tint of composite only affects the alpha channel.

**Comment by kutoman** [comment]
yes, since it works on the chosen composite item anyway. What I mean is not the tint color of the composite item itself, but the tint color of its children. Those changes (of the children's tint color) are affecting the chosen composite item but not the linked clones.

**Comment by azakhary** [comment]
Ah I see, will, take a look

**Comment by azakhary** [comment]
Oh I see. well that is intended behavior.
Let me try to explain:
When items are linked, it's actually their contents are linked for example if I have 2 linked composite. Whatever changes inside them (their children related) will change in other one. But otside composite properties like: tint, scale, position should not translate to linked items. Why? If you do tint, you also have to do position, and if we do position, then all linked items will be on same spot.

Look at it as in terms of coding. Library item is - Class. Actual on stage item is - instance object. If you change overall class structure, it affects all instance objects. But when you change instance variables/state it does not affect other instances.

**Comment by kutoman** [comment]
ok I kinda suspected that :)

**Comment by azakhary** [comment]
There was some serious issues going on with Library items though, I just fixed them in #299 by the way. Should be a lot more stable now. (Plus custom vars were not an entity modify command, so not updating library items, this yet has to be done for tags)
