### ISSUE TITLE
Unable to access jarfile /usr/share/java/overlap2d/overlap2d-*.jar

### ISSUE THREAD

**Issue by Gadzev** [UnderwaterApps/overlap2d#276]
Overlap2d wont start. When i run it in the terminal it gives the following error given in the title.

**Comment by azakhary** [comment]
It's a linux system tight? Do you have Java 1.8 installed? Does your user have permissions to run the file?

**Comment by Gadzev** [comment]
@azakhary yes it manjaro. I just installed java 1.8 and it still wont run, but when i run java -version in terminal it says i have 1.7.. 

I have permissions and even if i dont i tried running it as root and got the same error

**Comment by azakhary** [comment]
I see, I don't usually use Linux system for work, so not sure I can be very helpful.
But I assume that when you run java it is still pointing to 1.7 you probably can find where 1.8 is and run it specifically. Or whatever is the correct way to do it in linux. If I'd be you I will look for path of where 1.8 java is located, and will run it using full path, to see if that works.

**Comment by Gadzev** [comment]
@azakhary i have found a way to set the current version of java to be 1.8 and when i run overlap2d in the terminal it still gives me the same error....

**Comment by azakhary** [comment]
hmm, okay. good it works.

I am sure others may have same issue, and this thread will be useful for them.
