### ISSUE TITLE
[Bug] Impossible to move a dialog box with other window size

### ISSUE THREAD

**Issue by Honguito98** [UnderwaterApps/overlap2d#29]
1. Open the program.
2. Maximize.
3. Open any dialog, e.g.: Item physics editor.
4. Restore window
5. ...

![img_window](https://cloud.githubusercontent.com/assets/11828802/7017092/6ebe939c-dcb7-11e4-9865-b40273ea37ca.png)

**Comment by azakhary** [comment]
I am unable to reproduce, what is your screen resolution?

**Comment by Honguito98** [comment]
My computer resolution is 1920x1080.

**Comment by azakhary** [comment]
Not relevant anymore, as this dialog is purged in #75
