### ISSUE TITLE
Entity bounds are all wrong with scaling

### ISSUE THREAD

**Issue by nikoliazekter** [UnderwaterApps/overlap2d#296]
I made a gif that illustrates this bug. Scaling makes entity detect hits even outside its bounds. Also if entity gets downscaled before it was ever upscaled, it doesn't recieve clicks in a part of its bounds. And yeah, bounds (rendered rectangle) should respond to scaling immediately, not after clicking.
![bug](https://cloud.githubusercontent.com/assets/6832533/10915208/6d9d292c-825e-11e5-9075-d393fd53a2b5.gif)

**Comment by azakhary** [comment]
Oh, oups :D yeah this has to be fixed, and in both Input part that detects click, and in Follower part that makes the rect. The second one is probably easier.

**Comment by Sasun** [comment]
issues fixed
