### ISSUE TITLE
Cant open overlap2d  editor 0.1.1

### ISSUE THREAD

**Issue by bangive** [UnderwaterApps/overlap2d#297]
I am using windows 7 32 bit already install jdk 7, download editor file overlap2d.tar.gz and extract and click on jar file. But it throw an error "A java execption has occured".

**Comment by azakhary** [comment]
you need jdk 8, not 7

**Comment by bangive** [comment]
thank you, i will try to install jdk 8

**Comment by azakhary** [comment]
Let me know if it works or not! :)

**Comment by bangive** [comment]
I think android studio need jdk 7 how to solve this conflict

**Comment by azakhary** [comment]
oh you can totally have both.

**Comment by azakhary** [comment]
you can install both, point your android studio to the 7 (from settings) but make sure your JAVA_HOME is 8, so your jar files run on latest one. That's the right way to do it.

**Comment by bangive** [comment]
Thank you very much. It works.
