### ISSUE TITLE
How to create sprite animation

### ISSUE THREAD

**Issue by bangive** [UnderwaterApps/overlap2d#303]
I see in platformer repo has files sheep.atlas and sheep.png. How to create those files.

**Comment by azakhary** [comment]
Ig you just want to "get" it in order to use for testing in tutorial - you can find this files in demo project that comes with the editor when you download it. But if you are asking how to make a sprite animation - well I use Adobe Flash to do it.

**Comment by bangive** [comment]
Is there any other free software to do it?

**Comment by azakhary** [comment]
This is the only I know of: http://www.piskelapp.com/ But I am sure there will be others. Just search for them. This website: http://www.pixelprospector.com/ links to many cool tools, maybe you can also look there. Like for example you can use shoebox with combination with a graphics editor. You can also probably use spine "trial" version for limited time. Ask on animation forums or reddit I guess.

**Comment by bangive** [comment]
so much thanks

**Comment by azakhary** [comment]
You welcome :)
