### ISSUE TITLE
file not found project.dt when run desktop

### ISSUE THREAD

**Issue by bangive** [UnderwaterApps/overlap2d#306]
I am using overlap2d editor 0.1.1, overlap2d runtime 0.1.2-SNAPSHOT.
In Overlap2d exported resources to core/assets
I do not import projects to IntelliJ or Eclipse. I only use Sublime Text to code because my laptop is old and weak to run those IDE.
When i run desktop with gradle command line "gradlew desktop:run" it show error:
```
"LWJGL Application" ... File not found: project.dt <Internal>.
```
I think because it is not imported to an IDE. How can i resolve this without imported to an IDE.

**Comment by azakhary** [comment]
you do not export to "IDE" all you have to do is export into the assets folder from the editor.

**Comment by bangive** [comment]
I already export resource into assets folder at core/assets. I mean dont import project to IDE.

**Comment by azakhary** [comment]
that does not matter. 
can you confirm you core/assets contains project.dt file? or maybe if you have android app as well, it should be android/assets

**Comment by bangive** [comment]
It has project.dt. I have setup android and ios app as well. I am going to try to put it in android/assets as you recommad

**Comment by azakhary** [comment]
when you have android project, libGDX will look into android/assets so you should export all of assets there

**Comment by azakhary** [comment]
here is the doc on that: https://github.com/libgdx/libgdx/wiki/File-handling

**Comment by bangive** [comment]
This error is gone but another error is showing:
```
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at com.test.superninja.SuperNinja.render(SuperNinja.java:24)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
```
Here is the code of SuperNinja.java:
```
package com.test.superninja;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.uwsoft.editor.renderer.SceneLoader;

public class SuperNinja extends ApplicationAdapter {
	
	private SceneLoader sceneLoader;
	
	@Override
	public void create () {
		SceneLoader sceneLoader = new SceneLoader();
		sceneLoader.loadScene("MainScene");
	}

	@Override
	public void render () {
		Gdx.gl.glClearColor(0, 0, 0, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		sceneLoader.getEngine().update(Gdx.graphics.getDeltaTime());
	}
}

```

**Comment by azakhary** [comment]
change this SceneLoader sceneLoader = new SceneLoader(); to sceneLoader = new SceneLoader();
You already have it is class member variable, now you initialize it again which results in null pointer.

**Comment by bangive** [comment]
thank you for fast reply. It works. Have a good day.
