### ISSUE TITLE
Can't load particles from libgdx particle editor without png to them

### ISSUE THREAD

**Issue by Nitheism** [UnderwaterApps/overlap2d#309]
I used the libgdx particle editor to make simple smoke particle but I havent used any pngs to make it I save it with extension .p but in overlap2d I cant import it, when I opened the exported file and I realized that there is by default path to image.png which I dont have i deleted the whole image paragraph but I still cant import it to overlap2d.

**Comment by azakhary** [comment]
Got it. It's kind of a particle editor thing. When you do not use any png's they use their default "particle.png" which exists but only in memory of that app. 
Here is that image: https://github.com/libgdx/libgdx/blob/master/extensions/gdx-tools/assets/particle.png

You can download it and put near your particle before importing.  In that case when imported, the image will be added to your atlas and things will work.
