### ISSUE TITLE
sheep fall through the ground not stand on it.

### ISSUE THREAD

**Issue by bangive** [UnderwaterApps/overlap2d#312]
When i run desktop, the sheep fall down through the ground not stand on it.
I realized that i did not create physic body for ground then i try to create. I export than run but give the following error.
```
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at com.uwsoft.editor.renderer.systems.PhysicsSystem.processEntity(Physic
sSystem.java:36)
        at com.badlogic.ashley.systems.IteratingSystem.update(IteratingSystem.ja
va:66)
        at com.badlogic.ashley.core.Engine.update(Engine.java:314)
        at com.test.superninja.SuperNinja.render(SuperNinja.java:36)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplic
ation.java:215)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplicati
on.java:120)
```
Here is the SuperNinja.java
```
package com.test.superninja;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.uwsoft.editor.renderer.SceneLoader;
import com.badlogic.gdx.utils.viewport.Viewport;
import com.badlogic.gdx.utils.viewport.FitViewport;
import com.uwsoft.editor.renderer.utils.ItemWrapper;


public class SuperNinja extends ApplicationAdapter {
	
	private SceneLoader sceneLoader;
	private Viewport viewport;
	private ItemWrapper root;
	private Player player;
	
	@Override
	public void create () {
		viewport = new FitViewport(160, 266);
		sceneLoader = new SceneLoader();
		sceneLoader.loadScene("MainScene", viewport);
		root = new ItemWrapper(sceneLoader.getRoot());
		player = new Player();
		root.getChild("player").addScript(player);

	}

	@Override
	public void render () {
		Gdx.gl.glClearColor(0, 0, 0, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		sceneLoader.getEngine().update(Gdx.graphics.getDeltaTime());
	}
}
```

**Comment by azakhary** [comment]
This kind of questions regarding tutorials are not a representation of editor bug. They should go to runtime repo if it's a runtime bug, or if just a programming question they should go to the forums.

**Comment by azakhary** [comment]
(As for the problem itself, check from the editor if "enable physics" checkbox is ticked.

**Comment by bangive** [comment]
Sorry for this, i will post kind of this question to forum another time.
I already checked "enable physics". I think because i create physic body wrong. Please show me how to create ground.

**Comment by azakhary** [comment]
When you create physics body, then from editor add 2 components, one physics component, another polygon component. for polygon component also click "create default" to create default "rectangle" From that moment it should be well set up. Can you confirm you have added both components?

**Comment by bangive** [comment]
Please tell me step by step.
Now i am on the step of right click on ninepatch ground. What i need to do next.

**Comment by azakhary** [comment]
on the right panel there is select box with list of components, there are 3 elements, shader component, physics component and polygon component. add physics component and polygon component, do not add shader component. This will add some new elements to the properties box like button called "create default". click it. That's it.

**Comment by azakhary** [comment]
![helphysics](https://cloud.githubusercontent.com/assets/2115888/11145675/1af211fe-8a21-11e5-8050-ca907bf9d6b3.png)

I hope this explains it.

**Comment by bangive** [comment]
I've done what you said. Now it does not show error but the sheep still fall through the ground.

**Comment by azakhary** [comment]
Then you probably did something wrong, but it's really hard to tell what unless people see your sources and o2d poject. Please post this question on forums with reference to this issue, to see if others may be able to help you out. I am going to close this issue, as this is not overlap2d related issue.

**Comment by azakhary** [comment]
![help2](https://cloud.githubusercontent.com/assets/2115888/11145757/f0f29cd8-8a21-11e5-8cc2-83f9e6b7e0a7.png)

Try checking this. when you choose polygon tool, check if yellow rectangle is visible around your ground.

**Comment by azakhary** [comment]
Other thing you can do is download this: https://github.com/azakhary/platformer_tutorial
And compare to yours, see what the differences are.
Because that example works.

**Comment by bangive** [comment]
Thank you for your help i will try it now.

**Comment by bangive** [comment]
Do i need to create physic body and polygon for sheep

**Comment by azakhary** [comment]
no. not for this tutorial, because we use raycasting

**Comment by bangive** [comment]
thank you very much, i am going to compare now.

**Comment by bangive** [comment]
I cannot resolve it so i already post to overlap2d forum [here](http://overlap2d.com/forums/topic/the-sheep-fall-through-the-ground-not-stand-on-it/). If you have time please help me more. Thank you for your kind.

**Comment by bangive** [comment]
I've tried to run platformer_tutorial. I update extensions to newest version in build.gradle. But it show error. I already posted on runtime repo [here](https://github.com/UnderwaterApps/overlap2d-runtime-libgdx/issues/61)

**Comment by bangive** [comment]
In part 1 i don't see you implement raycasting why the sheep can stand on the ground.

**Comment by bangive** [comment]
Its sad I have followed to third tutorial video but cannot make it works. Please help me.
