### ISSUE TITLE
Loading asset from library in LIGDX?

### ISSUE THREAD

**Issue by Nitheism** [UnderwaterApps/overlap2d#318]
Hello, I made a project with Overlap2D I added some assets to the screen and added them to library, I havent created any library so guess it is the default one. Then after I added them to library I deleted them from screen, but how should I reach them and add script to them, or add them as actors of a Stage from SceneLoader, since I dont have anything such as getCompositeById or tag ot name or something like that I only got loadFromLibrary but I don't know my library's name and even if I did  I still can't laod particular asset? Can someone explain to me how it is done, loading asset from library to actor Texture, ot just for adding script to it? I use the 0.1.2-SNAPSHOT, but I use Stage class for the stage, also I don't even have CompositeItem as class or is it different in the new runtime?

**Comment by Nitheism** [comment]
I would appriciate if someone showed me a simple example code just for the purporse to see how can I get a sprite from the default library and assign it to CompositeActor

**Comment by azakhary** [comment]
when you add things to library in editor, they show up in the right middle panel in (Library" tab.
The name of library item is given by you, when you clicked convert to library button, it asked for a name, and you wrote it there.

Now from your code. all you need to do is retrieve it.
There is a method in SceneLoader, that will give you CompositeItemVO type from library. Look for it.
using that method you can get the VO object. Then. Create CompositeActor class (It's  the new CompositeItem) in it's constructor pass the VO object. That will create the actor from library. You can now add this actor to a stage.

**Comment by azakhary** [comment]
The best way to get answers to runtime related questions is to post them here:
http://overlap2d.com/forums/forum/runtimes/libgdx-runtime/

This is an issue tracker for Bugs that happen inside the editor, so that they can be fixed in the editor source code. Since this is not an editor bug, but a runtime question. I am closing this thread. Please repost in forum, if my answer did not help.
