### ISSUE TITLE
Rotation of Cone Lights doesn't work

### ISSUE THREAD

**Issue by nchuck** [UnderwaterApps/overlap2d#320]
I've tried to rotate it by drag/scroll, rotation property and nothing happens, it just stays there, with default position.
Even when loading the scene, it stills the same.

**Comment by azakhary** [comment]
I'll check this out. Thanks for reporting.

**Comment by azakhary** [comment]
Partly fixed in #325 while no fancy solution like "rotation affecting degree" or mouse scroll usage. It now has a "so so" solution: you can set cone degree with additional field in cone light settings panel

**Comment by nchuck** [comment]
Thanks! You guys are doing an amazing work
