### ISSUE TITLE
Can't remove image resource from the project using "Resources" panel

### ISSUE THREAD

**Issue by ihitang** [UnderwaterApps/overlap2d#328]
Steps to reproduce:
1. create new project 1920*1200, pixel per WU 1
2. import image resource 
3. add image to the editor
4. add new resolution 800*480
5. export
6. try to remove the image (right mouse button / delete)

**Comment by HetIsNiels** [comment]
I have (almost) the same problem. After converting an image to ninepatch, can't remove it now.

**Comment by azakhary** [comment]
hmm I get it, it's related to .9 at the end of the file, the remove procedure has to take this into account, should be an easy fix.

**Comment by azakhary** [comment]
The quick solution for you (before we fix it) will be to delete that 9 patch from all the scenes, then delete it from assets/orig/images folder, and click "repack"

**Comment by HetIsNiels** [comment]
Editing the project files (while the project was closed) worked for me.

**Comment by arnoid** [comment]
@HetIsNiels Which files you were editing?

**Comment by Sasun** [comment]
issue fixed
