### ISSUE TITLE
[Suggestion] Slightly change Rulers' Guides

### ISSUE THREAD

**Issue by billzo** [UnderwaterApps/overlap2d#334]
Since Rulers don't seem to have a "Properties" menu, it can be pretty hard to get them to be an exact number of World Units, like 5.25, or 5.5.

I think it would be very useful to:

1) Represent the small pop-up of World Units to the nearest 100th, instead of rounding to nearest full number,
2) Snap the Ruler at nearest whole numbers, and
3) Add a "Properties" menu for the Rulers that allows the user to input the exact World Units amount to the nearest 100th

**Comment by billzo** [comment]
Also, I would more than happy to do this. I actually don't think I can assign it though... Sorry, not overly familiar with GitHub..

**Comment by billzo** [comment]
Instead of a Properties menu, I think just being able to Right Click on a ruler and change the X and Y value manually via a drop-down list would work just fine... I've implemented 1, and 2. And in the process of doing 3.

**Comment by azakhary** [comment]
It tries to smartly choose the next rounding number based on the zoom. Kind of like photoshop does it. That's for the rulers. But are you talking about guides or rulers? so when you try to position the guide, it's hard to get it right and makes sense to have properties menu for it. Let's talk about this some more. I want to understand what the exact issue is.

**Comment by billzo** [comment]
I definitely meant Guides, sorry.. I was just looking at the RulersUI class, and I'm referencing the the Guide that is displayed on the screen. I needed to make a Scene with a width 5.5 World Units, and it was hard to get it just right because of the pop-up not reflecting beyond whole numbers in World Units.

Here's what I'm thinking.

Right click:
![right_click_on_guide](https://cloud.githubusercontent.com/assets/7116834/11979127/c67d24b2-a95e-11e5-842c-05b2373c2a0b.png)

Input:
![change_guide](https://cloud.githubusercontent.com/assets/7116834/11979140/ddbe5e0c-a95e-11e5-8c50-783da6393a93.png)

Dragging:
![dragging](https://cloud.githubusercontent.com/assets/7116834/11979229/a907ab54-a95f-11e5-8f8b-e3bf245757d1.png)

Also, I'm thinking of having the Guide snap to both quarter numbers, as well as halves. I think it's much more likely someone will need a Guide at 5.25 than 5.26, for example. But if they do, they can always right click on it and input the number manually.

As for the Properties menu, I might still look into that myself, but I'm not familiar with the Inheritance structure of the code to do it correctly... RulersUIMediator already extends SimpleMediator, so it can't extend UIBasicItemProperties... Unless I'm missing something.

**Comment by billzo** [comment]
Oh, and I just realized we don't know both a Guide Position for both X and Y, since the Guide can only either be X or Y.... I'll fix that.

**Comment by billzo** [comment]
Okay, I'm happy with it for now. I committed the changes to my fork. If you'd like to take a look.

**Comment by azakhary** [comment]
Awesome! this is perfect, can you do a pull request so I can take a look?

I think this is good enough, as for the property box, I'll do it myself!

**Comment by billzo** [comment]
Great! I'm glad to help.
