### ISSUE TITLE
OS X change Z index shortcut not working

### ISSUE THREAD

**Issue by qaze** [UnderwaterApps/overlap2d#339]
In documentation mentioned that we can use Control+Up to change Z index of object.
But it's not working on OS X due to this shortcut used for system.

Maybe can change it for CMD+Up on OS X?

**Comment by qaze** [comment]
Fixed it on my fork. Can create pull request

**Comment by azakhary** [comment]
Awesome, thanks a lot, I'll check and merge soon

**Comment by qaze** [comment]
Not an issue
