### ISSUE TITLE
BUG editor cut, paste shortcuts mac osx

### ISSUE THREAD

**Issue by postpunkpl** [UnderwaterApps/overlap2d#35]
Shortcuts for cut, paste don't work on mac osx. It works only from application menu.

**Comment by azakhary** [comment]
Do you test the jar file with 0.0.7 version, or the latest build from codes on master branch?

**Comment by postpunkpl** [comment]
the same problem with other shortcuts like Export or save, I use 0.0.7 version

**Comment by postpunkpl** [comment]
is there any latest build of editor at github? I can't find them, only source code. Do i need to build latest editor from sources?

**Comment by azakhary** [comment]
If you want latest build I am afraid yes you have to build from sources, but I will try to but up a last non-stable build somewhere tomorrow or today.

**Comment by postpunkpl** [comment]
when i'm trying to build editor from Intellij i have that error:

Error:java: invalid source release: 8

Does editor need JDK 1.8?

**Comment by azakhary** [comment]
yep, sorry about that, it requires JDK 1.8 (and also the instructions in README)

**Comment by postpunkpl** [comment]
i'm affraid that i have too many errors to build it myself

eg:

/Applications/overlap2d/src/com/uwsoft/editor/data/migrations/migrators/VersionMigTo005.java
Error:(28, 39) java: package com.uwsoft.editor.renderer.data does not exist
Error:(29, 39) java: package com.uwsoft.editor.renderer.data does not exist
/Applications/overlap2d/src/com/uwsoft/editor/gdx/ui/LibraryList.java
Error:(37, 40) java: package com.uwsoft.editor.renderer.actor does not exist
Error:(38, 40) java: package com.uwsoft.editor.renderer.actor does not exist

etc

**Comment by jacktech24** [comment]
you have to read the instructions, then you will have no problem to build it

> Fork this repo
> Clone your fork to your local
> Overlap2D requires for it to be in same folder in which o2d runtime and spine runtime are located so you need to clone them separately
> Clone overlap2d-runtime from here (and switch it to dev branch)
> Clone spine runtimes from here
> Make sure that paths are correct by taking a look (not modifying) settigs.gradle of overlap2d project
> Open your favorite IDE (Eclipse/IntelliJ) and import overlap2d as gradle project
> Things should work fine now, create branch, make some commits, push it to your origin and make some pull requests - yay ^^

you probably forgot the part with
> Clone overlap2d-runtime from here (and switch it to dev branch)
> Clone spine runtimes from here

**Comment by whitegfx** [comment]
I have similar issues, but when I set JDK 1.8 for gradle and switched to dev branch for libgdx runtime all works fine. Clean and builded without any error on mac osx.

7. 4. 2015 v 17:07, postpunkpl <notifications@github.com>:

**Comment by postpunkpl** [comment]
i'm sorry for that beginner question, but how to "set JDK 1.8 for gradle"?

2015-04-07 18:26 GMT+02:00 whitegfx <notifications@github.com>:

**Comment by whitegfx** [comment]
o2d Gradle build script need 1.8, so will use default runtime from your environment/project/IDE. If you have 1.8 will be ok.
If you have 1.7 or less on mac osx, download 1.8 jdk fro moracle site and install it. In the IDE you can change runtime for gradle in the specific project options.
I use eclipse and all mentioned is from eclipse. If you have other IDE try find some project runtime change tutorial for you favorite IDE.
One last thing maybe important, in the eclipse I need to install gradle plugin to handle gradle build scripts/settings.

GL

7. 4. 2015 v 18:33, postpunkpl <notifications@github.com>:

**Comment by postpunkpl** [comment]
so i have 1.8 and still that errors at IntelliJ

2015-04-07 19:01 GMT+02:00 whitegfx <notifications@github.com>:

**Comment by kutoman** [comment]
Go to:
File (menu) -> Settings -> Build,Execution,Deployment -> Build Tools -> Gradle
and choose 1.8 as Gradle JVM

**Comment by postpunkpl** [comment]
Kutoman, there is no Gradle JVM option, please look at this:

[IMG]http://i60.tinypic.com/2e5ruvn.png[/IMG]


2015-04-07 19:24 GMT+02:00 kutoman <notifications@github.com>:

**Comment by postpunkpl** [comment]
Dear Filip Prochazka,

You have right, i don't have good structure of external repos. Now
everything works! Thank You so much.
​
