### ISSUE TITLE
"Add to library" can not input text on MacOS

### ISSUE THREAD

**Issue by zaynyatyi** [UnderwaterApps/overlap2d#355]
When i'm trying to add object to the library on macOs i can't enter it's name in letters. I can enter numbers only or name with letters from clipboard.

**Comment by zaynyatyi** [comment]
It happens not every time

**Comment by azakhary** [comment]
hmm. that's weird. No way to reproduce? I am trying on my mac with no success.

**Comment by zaynyatyi** [comment]
Sometimes it works well, but sometimes there are weird UI issues. Seems it's rare issue. I will reopen if i will find way to reproduce.
