### ISSUE TITLE
Can not move the edited image !!!!

### ISSUE THREAD

**Issue by tianqiujie** [UnderwaterApps/overlap2d#372]
I move a image to the editor , and edit , but can not move!!!!  The bug is very serious ！Please help !!!
![1](https://cloud.githubusercontent.com/assets/2835129/13723827/eaa594dc-e8ab-11e5-8a08-f13d8e92c79e.gif)

**Comment by soapysoft** [comment]
not a fix, but right-click and convert to compositeItem before you resize it.

**Comment by Sasun** [comment]
issue fixed
