### ISSUE TITLE
v0.0.8 darker than v0.0.7

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#38]
the editor itself has kinda a grey ambient color already..
![image4144](https://cloud.githubusercontent.com/assets/5825645/7048427/54e6d1de-de13-11e4-8a57-e51a7b8413d5.png)

**Comment by Hohenheimsenberg** [comment]
Uncheck disable ambiance

**Comment by azakhary** [comment]
hmm. that's weird though.

**Comment by azakhary** [comment]
Just pushed a temporary fix, but still puzzled why this was working on one machine, and not on my other... weird. pull, let me know if it got fixed for you?

**Comment by kutoman** [comment]
yes, it got fixed!
