### ISSUE TITLE
Field not found: pixelToWorld

### ISSUE THREAD

**Issue by Mydelin** [UnderwaterApps/overlap2d#385]
E/AndroidRuntime(803): com.badlogic.gdx.utils.SerializationException: Field not found: pixelToWorld (com.uwsoft.editor.renderer.data.ProjectInfoVO)

Estoy usando overlap 0.1.0

**Comment by Mydelin** [comment]
![image](https://cloud.githubusercontent.com/assets/11493750/14593352/aa538ffe-04e6-11e6-9812-095839a00770.png)

![image](https://cloud.githubusercontent.com/assets/11493750/14593363/c56a1d80-04e6-11e6-86ea-72ce47ab1e94.png)

![image](https://cloud.githubusercontent.com/assets/11493750/14593374/ea150348-04e6-11e6-8452-925197570f5d.png)

![image](https://cloud.githubusercontent.com/assets/11493750/14593389/1f004680-04e7-11e6-81c7-e1a8499d3e54.png)

**Comment by azakhary** [comment]
you seem to be using either old depricated runtime or old depricated editor. This are not supported. Thus file save format incompatibility error.
