### ISSUE TITLE
Compile error in ItemFactory.java, fresh clone.

### ISSUE THREAD

**Issue by agmcleod** [UnderwaterApps/overlap2d#39]
Hello,

Wanted to give this whole setup a try. I cloned this, the runtime repo, and the spine repo. Setting it up in IntelliJ with JDK 1.8, i then setup a run configuration and tried to build. Got the following error:

Error:(165, 29) java: cannot find symbol
  symbol:   variable skeletonData
  location: variable itm of type com.uwsoft.editor.renderer.actor.SpineActor

The error coming from here: https://github.com/UnderwaterApps/overlap2d/blob/d58ace645308418e72724fd1713c511b9605c3d4/src/com/uwsoft/editor/gdx/sandbox/ItemFactory.java#L165

Checking the Spine Actor class in the runtime repo, it seems to have the skeletonData sections commented out.

**Comment by azakhary** [comment]
have you switched to dev branch on runtime repo, as it was mentioned in README ?

**Comment by agmcleod** [comment]
Ack, sorry i did miss that. Hit sync & ran build. Doesn't seem to be resolving the `com.esotericsoftware` package from spine-runtimes. Module is there though, and i can see the files under src. The settings.gradle looks fine too.

**Comment by azakhary** [comment]
should have helped, the dev branch of runtime contains the non-reflection normal spine referencing, maybe try to run gradle clear task ?

**Comment by azakhary** [comment]
#23 #13 were similar issues

**Comment by agmcleod** [comment]
Ran a gradle clean, and did a build. Do i need to add run configs for the other modules?

**Comment by azakhary** [comment]
no, not really. it should be working.

**Comment by agmcleod** [comment]
Ah okay. Yeah was getting the same error.

Restarted Idea, ran gradle sync. Getting it to compile now. But it's complaining about me using the JDK over JRE lol.

**Comment by azakhary** [comment]
How is it complaining? :D  is it running, or?

**Comment by agmcleod** [comment]
Console:

    2:03:49 PM Compilation completed with 1 error and 0 warnings in 2 sec
    2:04:03 PM Compilation completed successfully in 5 sec
    2:04:03 PM Error running Overlap2d: Jre expected but jdk found

Nothing running :)

**Comment by azakhary** [comment]
O_O I am running with JDK 8... not sure why jre is expected

**Comment by azakhary** [comment]
do you run it with gradle run task?

**Comment by agmcleod** [comment]
Ah that would do it. i used a run config in intellij, not the gradle task. Cheers!

**Comment by azakhary** [comment]
Awesome! glad it worked :)
