### ISSUE TITLE
[BUG] 0.0.8 Unable to resize an image while zooming

### ISSUE THREAD

**Issue by RgehanProjects** [UnderwaterApps/overlap2d#41]
When the zoom is different from 100%, it's quite hard to grab the resizing handles.

**Comment by azakhary** [comment]
Same goes with grabbing handles of rotated item.  ( #12  )
I will try to change mechanism of that, to solve both.

**Comment by RgehanProjects** [comment]
Thanks then :)

**Comment by azakhary** [comment]
Mechanism changed in #75
