### ISSUE TITLE
Resizing the app window seems kinda broken

### ISSUE THREAD

**Issue by sh-dave** [UnderwaterApps/overlap2d#411]
Whenever i try to resize overlap's window with an opened project, it just goes nuts.
Moving it to another display has the same effect (main monitor: 1920x1200, secondaries: 1920x1080 or 1280x1024). It seems to work fine when no project is open though.

Overlap2d-0.1.3, Windows 8; JRE 1.8.0_71

![image](https://cloud.githubusercontent.com/assets/13007175/16322022/a6e34924-39a0-11e6-90ab-10e84e35c14d.png)

**Comment by bruceloco** [comment]
Did you get the menus not going up/down?

**Comment by sh-dave** [comment]
The whole UI is broken. The picture is a full shot of the overlap window. Mainmenu gone, Toolpanel gone, Properties/Resources gone, whats left of the Items-Tree broken, the displayed scene scales randomly.
