### ISSUE TITLE
Atlas for spriter animation assets

### ISSUE THREAD

**Issue by sh-dave** [UnderwaterApps/overlap2d#412]
Just imported a spriter animation into my project, exported it and it doesn't generate an atlas file like it does for images or ninepatches.

**Comment by LoveraSantiago** [comment]
If you have not solved this problem. You can try using the TexturePacker libgdx to transform sprites in Atlas.

Att

**Comment by azakhary** [comment]
where do you look for that atlas?

**Comment by LoveraSantiago** [comment]
Me or sh-dave?
