### ISSUE TITLE
[Suggestion] Switching from a textfield to another with TAB

### ISSUE THREAD

**Issue by RgehanProjects** [UnderwaterApps/overlap2d#42]
It would be great if we could switch from a textfield to another with the TAB key. It's a feature of many softwares and I often find myself pressing it hoping for it to happen.

**Comment by DarthJDG** [comment]
+1, it's a very important feature to have.

**Comment by azakhary** [comment]
We are working on it btw, as the UI system is completely changed now, the switching with TAB will work automatically. As soon as I merge what we were working on, we will ping back on this issue.

**Comment by azakhary** [comment]
Done in #75
