### ISSUE TITLE
[BUG] 0.0.8 Undo is unpredictable

### ISSUE THREAD

**Issue by RgehanProjects** [UnderwaterApps/overlap2d#45]
You might already know it, but the undo action in the editor (at least on the 0.0.8 version) is quite unpredictable. Sometimes it undoes only one action, sometimes it's two of them, and sometimes more.

I thought at first it was related to different kind of save points, but it seems to be something different.

To reproduce it:
* Take an object (I used an image)
* Move it once somewhere
* Move it somewhere else
* Once again
* Then Ctrl+Z, and it's going to be kind of randomly rewinded to some place it used to be.

(Sorry for the broken english)

**Comment by azakhary** [comment]
Undo us super changed starting from #75 and this one is fixed.
If they are some other problems with Undo/Redo please report. But as of new architecture, they should be very rare, and easy to fix. (while previously it was impossible)
