### ISSUE TITLE
[Bug] 0.0.7 Physics shapes bug

### ISSUE THREAD

**Issue by RgehanProjects** [UnderwaterApps/overlap2d#46]
Hi,

Sorry to flood the bug tracker, but these are real problems.
I've been experimenting with the editor, and after exporting for the tenth time, the shape of my wheel changed all alone. Some vertices moved to the bottom left corner of the window. Don't know why, don't know if you can reproduce it.

What I did:
* Placing a few objects on the canvas like the tutorial (a few images + composities)
* Place the ball, edit its shape so it looks like an octogon
* Move it around, export it, test on Eclipse, rinse and repeat (about 10 times)

Please see this image:
![ball_bug](https://cloud.githubusercontent.com/assets/5821910/7071231/5b609abe-dee4-11e4-8491-d64c55c003d4.png)

What's weird is that it added two more vertices.

**Comment by RgehanProjects** [comment]
This view might help you. I managed to reproduce the bug, once again, and it seems like it's adding two more vertices, but not a the same place. The distance between them is almost like the diameter of the ball, or the shape I made.
It might have a link with the green line ?

Here is a picture
![another_view](https://cloud.githubusercontent.com/assets/5821910/7071425/7e340c78-dee5-11e4-864f-59b71315d47f.png)

**Comment by azakhary** [comment]
I see if I can reproduce this tomorrow

**Comment by RgehanProjects** [comment]
If you need further informations about this bug, don't hesitate.

**Comment by azakhary** [comment]
Fixed in #75
