### ISSUE TITLE
Crashed in Physics Editor, not sure how to reproduce it. 

### ISSUE THREAD

**Issue by Portals** [UnderwaterApps/overlap2d#57]
Stacktrace:
http://pastebin.com/VqTN1Zme

Using 0.07

**Comment by RgehanProjects** [comment]
Happened to me too. It seems to occur when your playing in physics test mode, but also when your working on the shape of your collider. Weird.

**Comment by Portals** [comment]
Seems like you're using the event thread to retrace, you should create some sort of runnable pool to later run it the main thread. Using the event thread might make the input less responsive. Because you're using a different thread the data might not have been saved (which is null and causes the exception).

**Comment by azakhary** [comment]
this is one of the parts that I have not written. @gevorg-kopalyan is them an behind it.
@gevorg-kopalyan can you take a look?

**Comment by gevorg-kopalyan** [comment]
Sure will take a look near days

**Comment by azakhary** [comment]
Physics editor is changed a lot from #75
