### ISSUE TITLE
Cannot Import Spine Animations

### ISSUE THREAD

**Issue by ThaBalla1148** [UnderwaterApps/overlap2d#64]
Steps To Reproduce:
* Use Overlap2D's Stable Build (0.0.7) and Public Alpha (0.0.8)
* Export a Project from Spine as a JSON, with Create atlas enabled
 * Creates xxx.atlas, xxx.json, and xxx.png
* Import into an Overlap2D Project as Spine/Spriter Animation (Selecting the xxx.json file)

Once you start the import, you will receive the error: **javax.imageio.IIOException: Can't read input file!**

After investigating, the xxx.png file isn't in the new directory when it tries to read this file at this point: **TextureUnpackerFixed.java:98**

After putting a break point there, and manually copying the xxx.png file there, it imports correctly.

I believe it may be caused by **DataManager.java:340**, it which it is looking for "- Image Path -", which is not in the xxx.atlas file.

It now begins to initialize the SpineActor, but we receive a **NullPointerException** here: **SpineActor.java:104**, because it is looking for a Spine bone named "root", which doesn't exist. Spine does not seem to create a bone with this name, nor have I read anything that implied to do so. Renaming the root bone to "root" fixes this. However, the Spine asset does not show under assets, could be because of the spine resolution.

Please let me know if you need more details.

**Comment by azakhary** [comment]
Working on it right now, I fixed the first part with old atlas file processing. Now it imports fine. And works for me, because my spine animation does have a root bone. I am going to create a new spine animation now to see if they changed something and it does not have root bone anymore?

**Comment by azakhary** [comment]
so problem part 1 is fixed in #65

**Comment by azakhary** [comment]
So I am looking here: http://esotericsoftware.com/spine-using-runtimes 
What I need is to scale it, and documentation says:
BoneData root = skeletonData.findBone("root");
root.scaleX = 2;

which is I guess out of date...

**Comment by azakhary** [comment]
Fixed in https://github.com/UnderwaterApps/overlap2d-runtime-libgdx/pull/28 & #65

Kind of a temp fix imho. The spine docs are out of date, and there is no more root bone, so I am using bone 0 to scale, but maybe there is a better way to scale now? Let me know.

Meanwhile pull both runtime dev branch and latest o2d master for fix. I will put latest jar, at the end of the week.

**Comment by ThaBalla1148** [comment]
That was pretty quick. This issue is fixed. I have noticed some issue with scaling a spine object imported into Overlap2d Editor. It doesn't seem to do any Y scale when you set it. When I scale the X and Y down, it throws off the animation, and the surround item box does not fit around the actor. I may investigate some more into it when I get the time and create a new issue.
