### ISSUE TITLE
build "instructions" insufficient

### ISSUE THREAD

**Issue by chriscamacho** [UnderwaterApps/overlap2d#68]
the instructions such as they are too vague and cloning git repos various and running gradlew and stabbing blindly at various buildNeeded etc doesn't work

there is no FAQ

missing KISS build system (ie ant - with default target that fetches/compiles all dependencies)

**Comment by DarthJDG** [comment]
It seems that the project is in a bit of a messy state at the moment, it doesn't seem to build as is. I'll fiddle with it a bit more in the coming days and see what happens.

One example is the simple button script in overlap2d-runtimes, which imports Align from the wrong package. It's been recently moved in the latest LibGDX releases, but it can't be built with the LibGDX version referenced in gradle. And there are numerous cases in this project as well, probable conflicts with latest Spine commits for example.

Care should be taken to keep all modules in sync or other repos should be included as git modules and point to a specific commit that's buildable.

**Comment by azakhary** [comment]
But  I surely agree this needs to be made simpler. Here is the current plan. there is a branch called "mvc" on my own fork. It is a huge thing we are working on at this moment. It will be using the "new runtime" one of the perks of new runtime is - there will be more dev versus master branch diversity. which will be a first step in making all a lot easier.

**Comment by DarthJDG** [comment]
That sounds great. That's obviously a huge change in the code. Do you have an ETA for the patch? There's probably not much point looking at the current codebase as I assume most PRs would be outdated. Last but not least, thanks for making this amazing project open source.

**Comment by azakhary** [comment]
I hope to merge in 2 weeks.

**Comment by azakhary** [comment]
FYI gotta happen probably today ;)

**Comment by azakhary** [comment]
Done :-P
