### ISSUE TITLE
Make it easy to run from sources

### ISSUE THREAD

**Issue by htynkn** [UnderwaterApps/overlap2d#71]
Hi All,

I follow the readme file and clone three repo to make overlap2d run from sources.

I just wonder if we can have the dependency through maven central or use git submodules to make it easy to run from sources?

Or there are any special reason that overlap2d didn't do this?

**Comment by azakhary** [comment]
There are 2 projects currently attached. 
one is overlap2D runtime,
other is spine runtime.

Spine runtime is not on maven, and I guess you have to ask Esotericsoftware why the decided to not put it there.
Overlap2D runtime uses spine runtime, so it can't be on maven unless we do a full reflection. But that one we are going to fix with upcoming new runtime, that so at least we will put that one up in maven.

One other thing to think about is, when doing changes on the editor, sometimes you want to modify runtime as well, and it is convenient when it is loaded from sources.

**Comment by htynkn** [comment]
You're right. Spine runtime is not on maven.
Thanks for your reply.It makes sense.
