### ISSUE TITLE
BadDrawable (LWJGLException) on ubuntu 14(64 bit)

### ISSUE THREAD

**Issue by wasimbeniwale** [UnderwaterApps/overlap2d#88]
Got this error when I try to run from terminal

"org.lwjgl.LWJGLException: X Error - disp: 0x7f4ce0382c40 serial: 158 error: BadDrawable (invalid Pixmap or Window parameter) request_code: 155 minor_code: 7"

**Comment by azakhary** [comment]
That happens for others on Linux as well. I am not sure why, but it is related to the way we do splash screen ( which has to change) would be cool if someone with Linux system can debug this.

**Comment by PkayJava** [comment]
I have just fixed this issue, and also did a pull request

**Comment by azakhary** [comment]
@wasimbeniwale I just merged @PkayJava 's pr, can you confirm that it did the trick?

**Comment by PkayJava** [comment]
yeah

**Comment by azakhary** [comment]
Okay I am closing this. If it does not work, please reopen :)

**Comment by devmpv** [comment]
Hi, after a fix I'm getting NPE exception in Main in the lines which where changed:
this is returning null: Main.class.getClassLoader().getResource("art/textures")
Maybe it is my setup? Just import as Gradle project in Eclipse.

**Comment by azakhary** [comment]
possible fixed at #96 will merge soon.

**Comment by devmpv** [comment]
For me there is no "art" folder in the classpath, instead its contents is located in /bin so 
if I change path to .getResource("textures") it is working but then I'm getting original error. Disabling splash screen helped before though.

**Comment by azakhary** [comment]
So at this moment I pushed a version that checks both fodlers to see if it's null or not.  If you test with latest master branch, will it be BadDrawable error only for you? If so we can fix it imho.

**Comment by azakhary** [comment]
I also noticed that for some reason if you use Intellij it uses assets/style and when you use Eclipse it goes to "style" folder without assets.

**Comment by devmpv** [comment]
It is all about classpath which is Gradle responsibility, dont know why its different.

**Comment by PkayJava** [comment]
I made a script which pull the latest update from all masters branches, overldap2d, overlap2d-libgdx-runtime, spine-runtime, visui, put it 2gether, that script work on linux, it might work on mac as well, 

https://github.com/PkayJava/overlap2d-dev

**Comment by azakhary** [comment]
wow. that's neat

**Comment by devmpv** [comment]
After update editor is starting fine, thank you

**Comment by azakhary** [comment]
Awesome!
