### ISSUE TITLE
Items Tree not (always) showing current selection

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#95]
If I select any item on the canvas, the Items Tree does not get updated and highlight the currently selected item.

**Comment by azakhary** [comment]
It only selects items that are children of the composit you are currently viewing. That is the intended behaviour.

**Comment by kutoman** [comment]
yeah sure, the selection over the items tree works just fine, but the highlighting (orange mark in the items tree) only happens properly when I pick from the items tree but not from the canvas. I would expect the items tree to be reactive to selection changes. The benefit would be that we automatically see the z-index of the current selection through the items tree.

**Comment by azakhary** [comment]
ah, got it! That should definitely be done.

**Comment by kutoman** [comment]
I could take this task?

**Comment by azakhary** [comment]
Yes! that would be awesome, no one so far has taken it, me included.

**Comment by azakhary** [comment]
Done by @kutoman in #143
