### ISSUE TITLE
Project corrupted when bad resources are imported

### ISSUE THREAD

**Issue by jymen** [UnderwaterApps/overlap2d#98]
This one may mainly be a 'show stopper' for newbies : 
Actually on 'import to library' selected resources are first copied to project directory and after loaded into project.
Since there are presently very few controlls on selected resources , if user select bad resources the load will crash and the project will allways crash until you manually cleanup the bad resource inside project directory manually 

Examples of potential crashes : 
- if you import a bad file format
- if you import particle file before importing used particle images into TextureAtlas

Proposed solution : postpone resource copy after successfull resource loading into project + extend resource loading controls

**Comment by azakhary** [comment]
I am currently making a mockup of new resource dialog based on your feedback. Will be posting here soon.

**Comment by azakhary** [comment]
Check out our new import dialog #104 
Now supports drag and dropping images. Currently does not you import bad file formats.
Although some crash cases still may be they have to be investigated and reported.

Can you check if any of your scenarios still apply so I can fix?

**Comment by azakhary** [comment]
I am closing this for now as there are no new reports. If something breaks again, please open new issue. Current new importing seems to work fine.
